### ISSUE TITLE
Does it not supports connect via unix domain socket?

### ISSUE THREAD

**Issue by shuge** [esnme/ultramemcache#34]
Start process

```
memcached -s /tmp/mc.sock
```

Test code

```
import umemcache

mc = umemcache.Client('unix:/tmp/mc.sock')
mc.connect()

print mc.set('a', 'b')
```

Got exception

```
Traceback (most recent call last):
  File "t.py", line 4, in <module>
    mc.connect()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```

**Comment by Jahaja** [comment]
No, there's no support for unix domain sockets, only TCP.
